"""initial database migration

Revision ID: a04c32543362
Revises: 
Create Date: 2020-02-13 12:19:39.298245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a04c32543362"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("data", postgresql.BYTEA(), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "document_hash",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("document_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=10), nullable=False),
        sa.Column("value", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["document_uuid"], ["document.uuid"],),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("value"),
    )
    op.create_table(
        "document_meta",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("time_of_creation", sa.DateTime(), nullable=False),
        sa.Column("creator", sa.String(length=100), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(["uuid"], ["document.uuid"],),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_meta")
    op.drop_table("document_hash")
    op.drop_table("document")
    # ### end Alembic commands ###
