apiVersion: apps/v1
kind: Deployment
metadata:
  name: docapi
  labels:
    app: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
      - name: tika
        image: logicalspark/docker-tikaserver
        ports:
        - containerPort: 9998
