apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: docapi-postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: password
        image: postgres:10-alpine
        name: docapi-postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: docapi-postgres-claim0
      restartPolicy: Always
      volumes:
      - name: docapi-postgres-claim0
        hostPath:
          path: /home/euro/Projects/minolta/kmle/storage/database
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: docapi-postgres
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
status:
  loadBalancer: {}

