apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tika
  name: docapi-tika
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
      - image: logicalspark/docker-tikaserver
        name: docapi-tika
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tika
  name: docapi-tika
spec:
  ports:
  - name: tika
    port: 9998
    targetPort: 9998
  selector:
    app: tika
status:
  loadBalancer: {}

